# Generated by Django 5.2 on 2025-04-17 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_remove_song_audio_file_song_audio_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='songs/images/'),
        ),
    ]
