# Generated by Django 5.2 on 2025-04-17 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_song_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
