# Generated by Django 5.2 on 2025-04-22 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_alter_song_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
