# Generated by Django 5.2 on 2025-04-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_artist_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
