# Generated by Django 5.2 on 2025-04-22 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_alter_likedsong_song_alter_likedsong_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikedSong',
        ),
    ]
